### ISSUE TITLE
Appending two query object

### ISSUE THREAD

**Issue by salarmehr** [FluentDOM/FluentDOM#34]
Please consider the following code:

```
$first = FluentDOM::QueryCss('<input/>');
$second = FluentDOM::QueryCss('<div></div>');
```
The first line works as expected.
  ```
   echo $second->find(':root')->append($first->document->toHtml())->document->toHtml(); // works
   echo $second->find(':root')->append($second->document->toHtml())->document->toHtml(); //failes
```
But, the second line fails with tho following exception:

```
Fatal error: Uncaught InvalidArgumentException: Invalid/empty content parameter. in D:\www\www\lab\vendor\fluentdom\fluentdom\src\FluentDOM\Nodes\Builder.php:108
Stack trace:
#0 D:\www\www\lab\vendor\fluentdom\fluentdom\src\FluentDOM\Query.php(242): FluentDOM\Nodes\Builder->getContentNodes('<input>\n')
#1 D:\www\www\lab\vendor\fluentdom\fluentdom\src\FluentDOM\Query.php(273): FluentDOM\Query->apply(Array, '<input>\n', Object(Closure))
#2 D:\www\www\lab\vendor\fluentdom\fluentdom\src\FluentDOM\Query.php(814): FluentDOM\Query->applyToSpawn(Array, '<input>\n', Object(Closure))
#3 D:\www\www\lab\qp-test.php(8): FluentDOM\Query->append('<input>\n')
```

Is there any workaround? Is there any more concise alternative two append a QueryCss tag to another one?

**Comment by ThomasWeinert** [comment]
Actually the fist call fails. 

`FluentDOM::QueryCss('<input/>')->document->toHtml()` results in `<input>`. This is invalid XML and `FluentDOM\Query::append()` expects a valid XML fragment is the argument is a string. XML contains more information (case sensitivity for example). FluentDOM is an XML library, HTML is only the secondary format and needs to be specified. In this case you could just append the nodes directly:

```php
$first = FluentDOM::QueryCss('<input/>')->find(':root');
$second = FluentDOM::QueryCss('<div></div>')->find(':root');
echo $second->append($first)->outerHtml();
````
